作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [8]:
import numpy as np

In [10]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

print(english_score)
print(math_score)
print(chinese_score)

[55 89 76 65 48 70]
[60. 85. 60. 68. nan 60.]
[65 90 82 72 66 77]


In [23]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
print("英文平均: %.2f" % np.mean(english_score),
      "英文最大值: %d" % np.max(english_score),
      "英文最小值: %d" % np.min(english_score), 
      "英文標準差: %.2f" % np.std(english_score))

英文平均: 67.17 英文最大值: 89 英文最小值: 48 英文標準差: 13.43


In [24]:
print("數學平均: %.2f" % np.nanmean(math_score),
      "數學最大值: %d" % np.nanmax(math_score),
      "數學最小值: %d" % np.nanmin(math_score), 
      "數學標準差: %.2f" % np.nanstd(math_score))

數學平均: 66.60 數學最大值: 85 數學最小值: 60 數學標準差: 9.71


In [25]:
print("國文平均: %.2f" % np.mean(chinese_score),
      "國文最大值: %d" % np.max(chinese_score),
      "國文最小值: %d" % np.min(chinese_score), 
      "國文標準差: %.2f" % np.std(chinese_score))

國文平均: 75.33 國文最大值: 90 國文最小值: 65 國文標準差: 8.83


In [26]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
math_score[4] = 55
math_score

array([60., 85., 60., 68., 55., 60.])

In [27]:
print("數學平均: %.2f" % np.mean(math_score),
      "數學最大值: %d" % np.max(math_score),
      "數學最小值: %d" % np.min(math_score), 
      "數學標準差: %.2f" % np.std(math_score))

數學平均: 64.67 數學最大值: 85 數學最小值: 55 數學標準差: 9.86


In [5]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [41]:
CE = np.corrcoef(chinese_score, english_score)
print(CE)

CM = np.corrcoef(chinese_score, math_score)
print(CM)

[[1.         0.97792828]
 [0.97792828 1.        ]]
[[1.         0.74056803]
 [0.74056803 1.        ]]


In [ ]:
關係數最高的學科...英文