作業目標<br>
在一個陣列中放入多屬性陣列，進一步對陣列做運算<br>
作業重點<br>
在建立結構化陣列前需要先設定屬性，在做運算時須注意資料屬性

題目:<br>
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']<br>
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']<br>
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]<br>
rank_list = [8,1,5,4,7,6,2,3]<br>
myopia_list = [True,True,False,False,True,True,False,False]<br>
1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]<br>
2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重


In [1]:
import numpy as np

In [5]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

In [6]:
#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，
# 並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]
dt = np.dtype('U5, U5, f2, i1, ?')
a = np.zeros(8, dtype=dt)
a

array([('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False),
       ('', '', 0., 0, False), ('', '', 0., 0, False)],
      dtype=[('f0', '<U5'), ('f1', '<U5'), ('f2', '<f2'), ('f3', 'i1'), ('f4', '?')])

In [7]:
a['f0'] = name_list
a['f1'] = sex_list
a['f2'] = weight_list
a['f3'] = rank_list
a['f4'] = myopia_list
a

array([('小明', 'boy', 67.5, 8,  True), ('小華', 'boy', 75.3, 1,  True),
       ('小菁', 'girl', 50.1, 5, False), ('小美', 'girl', 45.5, 4, False),
       ('小張', 'boy', 80.8, 7,  True), ('John', 'boy', 90.4, 6,  True),
       ('Mark', 'boy', 78.4, 2, False), ('Tom', 'boy', 70.7, 3, False)],
      dtype=[('f0', '<U5'), ('f1', '<U5'), ('f2', '<f2'), ('f3', 'i1'), ('f4', '?')])

In [9]:
#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重
b = a['f2']
b

array([67.5, 75.3, 50.1, 45.5, 80.8, 90.4, 78.4, 70.7], dtype=float16)

In [10]:
b_avg = sum(b)/len(b)
b_avg

69.83203125

In [13]:
#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重
boy_W = a[a['f1'] == 'boy']['f2']
boy_W
# sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
# weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]

array([67.5, 75.3, 80.8, 90.4, 78.4, 70.7], dtype=float16)

In [15]:
boy_W_avg = sum(boy_W)/len(boy_W)
boy_W_avg

77.17708333333333

In [16]:
#3. 呈上題，進一步算出女生(sex欄位是girl)平均體重
girl_W = a[a['f1'] == 'girl']['f2']
girl_W

array([50.1, 45.5], dtype=float16)

In [17]:
girl_W_avg = sum(girl_W)/len(girl_W)
girl_W_avg

47.796875